[package]
name = "sample_gem_rust"
version = "0.1.0"
edition = "2021"
authors = ["YutaGoto <12590762+YutaGoto@users.noreply.github.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.7.1" }
