name: rake

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  rake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3", "3.4"]

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies
        run: bundle install
      - name: run rake
        run: bundle exec rake
